<?php $posts = $this->getPosts(); ?>
<?php $post_max = 1; ?>
<?php $count = 1; ?>
<h3><?php print Mage::helper('blog')->__('Rational Kombid&auml;mpfer Blog'); ?></h3>
<?php if(count($posts)): ?>
	<?php foreach ($posts as $post): ?>
	 <?php if($count <= $post_max): ?>
<div class="postWrapper">
    <div class="postTitle">
        <h2><a href="<?php echo $post->getAddress(); ?>" ><?php echo $post->getTitle();?></a></h2>
		<h3><?php echo $post->getCreatedTime(); ?></h3>
    </div>
    <div class="postContent"><?php echo $post->getPostContent(); ?></div>
	<?php echo $this->getBookmarkHtml($post) ?>
	<div class="tags"><?php echo Mage::getBlockSingleton('blog/blog')->getTagsHtml($post) ?></div>
	<div class="postDetails">
		<?php if($this->getCommentsEnabled()): ?>
			<?php if($post->getCommentCount() == 1): ?>
			<?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Kommentar</a> | 
			<?php else:?>
			<?php echo $post->getCommentCount(); ?> <a href="<?php echo $post->getAddress(); ?>#commentBox" >Kommentare</a> | 
			<?php endif; ?>
		<?php endif; ?>
		<?php $postCats = $post->getCats(); ?>
		<?php if(!empty($postCats)):?>
			<?php echo Mage::helper('blog')->__('Ver&ouml;ffentlicht in');?>
			<?php foreach($postCats as $title=>$url): ?>
				<a href="<?php echo $url; ?>"><?php echo $title; ?></a> 
			<?php endforeach;?> 
<?php else:?>
	<?php echo Mage::helper('blog')->__('Posted');?>
<?php endif;?><?php echo$this->__("von");?> <?php echo $post->getUser(); ?></div>
</div>
<?php $count++; ?>
<?php endif; ?>
<?php endforeach; ?>
<?php endif; ?>